### ISSUE TITLE
Deprecation warning from sp::over

### ISSUE THREAD

**Issue by edzer** [apwheele/ptools#2]
Upcoming CRAN release for sp will cause a Deprecation warning from `ptools` for using `sp::over`; this happens in `dcount_xy`; I think you can easily prevent this by buffering `base` rather than `feat` - `over` will continue to work with points and polygons (for this, `rgeos` is not needed).

See https://github.com/edzer/sp/pull/127

**Comment by apwheele** [comment]
I don't see the issue here specifically, below `buff` is a spatial polygons dataframe, and feat is a spatial points dataframe. 

```
dcount_xy <- function(base,feat,d,weight=1){
   # Calculate buffers
   buff <- raster::buffer(feat,d,dissolve=FALSE)
   # Use over to count or sum
   if (weight == 1){
       ov_buff <- sp::over(base,buff[,1],fn=length)
   } else {
       ov_buff <- sp::over(base,buff[,weight],fn=sum)
   }
   ov_buff[is.na(ov_buff)] <- 0
   return(as.numeric(ov_buff[,1]))
}
```

------

My bad, I see now that it is two polygons. Going down the rabbit hole now to migrate off of rgeos and use sf instead in various places.

**Comment by apwheele** [comment]
Version 2.0 is up on CRAN and has removed the issues with sp::over and dependencies on rgeos, https://github.com/apwheele/ptools
